---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: nimatel.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: examples
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  instance_id: i-46136e1e
  image_type: t1.micro
  image_id: ami-26745463
  security_groups:
  - nimatel_production_default
  - nimatel_production_production
  - nimatel_production_apache
  - nimatel_production_app
  - nimatel_production_passenger
  - nimatel_production_collectd
  - nimatel_production_common
  - nimatel_production_monit
  - nimatel_production_db
  - nimatel_production_postgresql
  - nimatel_production_postgresql_master
  - nimatel_production_elasticsearch
  - nimatel_production_examples
  - nimatel_production_graphite_server
  - nimatel_production_graphite_web
  - nimatel_production_graylog_elasticsearch
  - nimatel_production_graylog_mongodb
  - nimatel_production_mongodb
  - nimatel_production_graylog_server
  - nimatel_production_graylog_web
  - nimatel_production_haproxy
  - nimatel_production_web
  - nimatel_production_web_tools
  external_host: ec2-54-215-4-156.us-west-1.compute.amazonaws.com
  external_ip: 54.215.4.156
  internal_host: ip-10-170-79-212.us-west-1.compute.internal
  internal_ip: 10.170.79.212
  zone: us-west-1c
  platform: linux
  root_device_type: ebs
  static_ip: 
- volumes: {}
  static_ips: {}
